definitions:
  internal.createPlayerRequest:
    properties:
      at_bats:
        example: 100
        format: int64
        type: integer
      hits:
        example: 30
        format: int64
        type: integer
      home_runs:
        example: 5
        format: int64
        type: integer
      name:
        example: 田中太郎
        format: string
        type: string
      runs_batted_in:
        example: 20
        format: int64
        type: integer
      uniform_number:
        example: 1
        format: int64
        type: integer
      walks:
        example: 10
        format: int64
        type: integer
    required:
    - at_bats
    - hits
    - home_runs
    - name
    - runs_batted_in
    - uniform_number
    - walks
    type: object
  internal.createPlayerResponse:
    properties:
      player:
        $ref: '#/definitions/internal.playerResponseModel'
    type: object
  internal.fetchPlayerResponse:
    properties:
      player:
        $ref: '#/definitions/internal.playerResponseModel'
    type: object
  internal.playerResponseModel:
    properties:
      at_bats:
        type: integer
      hits:
        type: integer
      home_runs:
        type: integer
      id:
        type: string
      name:
        type: string
      runs_batted_in:
        type: integer
      uniform_number:
        type: integer
      walks:
        type: integer
    type: object
  internal.searchPlayerResponse:
    properties:
      players:
        items:
          $ref: '#/definitions/internal.playerResponseModel'
        type: array
    type: object
host: localhost:50051
info:
  contact: {}
  description: 野球選手の成績を管理するAPIを提供する
  license:
    name: ライセンス(必須)
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Baseball API
  version: バージョン(1.0)
paths:
  /v1/players:
    post:
      consumes:
      - application/json
      description: 選手を作成する
      parameters:
      - description: User information
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/internal.createPlayerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal.createPlayerResponse'
      summary: 選手を作成する
      tags:
      - players
  /v1/players/{id}:
    get:
      consumes:
      - application/json
      description: 選手を作成する
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.fetchPlayerResponse'
      summary: 選手を取得する
      tags:
      - players
  /v1/players/crawl:
    post:
      consumes:
      - application/json
      description: '"https://baseball-data.com/stats/hitter-%v/tpa-1.html" から選手情報をクロールする'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: 選手情報のクロール
      tags:
      - players
  /v1/players/search:
    get:
      consumes:
      - application/json
      description: 選手を作成する
      parameters:
      - example: 10
        format: int
        in: query
        name: limit
        type: integer
      - example: 20
        format: int64
        in: query
        name: max_hits
        type: integer
      - example: 10
        format: int64
        in: query
        name: max_home_runs
        type: integer
      - example: 20
        format: int64
        in: query
        name: max_runs_batted_in
        type: integer
      - example: 10
        format: int64
        in: query
        name: min_hits
        type: integer
      - example: 5
        format: int64
        in: query
        name: min_home_runs
        type: integer
      - example: 10
        format: int64
        in: query
        name: min_runs_batted_in
        type: integer
      - example: hits
        format: string
        in: query
        name: sort_field
        type: string
      - example: asc
        format: string
        in: query
        name: sort_order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.searchPlayerResponse'
      summary: 選手を検索する
      tags:
      - players
swagger: "2.0"
