// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: grpc/proto/base_ball_api.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BaseBallApi_SelectPlayers_FullMethodName = "/BaseBallApi/SelectPlayers"
)

// BaseBallApiClient is the client API for BaseBallApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseBallApiClient interface {
	SelectPlayers(ctx context.Context, in *SelectPlayersRequest, opts ...grpc.CallOption) (*SelectPlayersResponse, error)
}

type baseBallApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseBallApiClient(cc grpc.ClientConnInterface) BaseBallApiClient {
	return &baseBallApiClient{cc}
}

func (c *baseBallApiClient) SelectPlayers(ctx context.Context, in *SelectPlayersRequest, opts ...grpc.CallOption) (*SelectPlayersResponse, error) {
	out := new(SelectPlayersResponse)
	err := c.cc.Invoke(ctx, BaseBallApi_SelectPlayers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseBallApiServer is the server API for BaseBallApi service.
// All implementations must embed UnimplementedBaseBallApiServer
// for forward compatibility
type BaseBallApiServer interface {
	SelectPlayers(context.Context, *SelectPlayersRequest) (*SelectPlayersResponse, error)
	mustEmbedUnimplementedBaseBallApiServer()
}

// UnimplementedBaseBallApiServer must be embedded to have forward compatible implementations.
type UnimplementedBaseBallApiServer struct {
}

func (UnimplementedBaseBallApiServer) SelectPlayers(context.Context, *SelectPlayersRequest) (*SelectPlayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectPlayers not implemented")
}
func (UnimplementedBaseBallApiServer) mustEmbedUnimplementedBaseBallApiServer() {}

// UnsafeBaseBallApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseBallApiServer will
// result in compilation errors.
type UnsafeBaseBallApiServer interface {
	mustEmbedUnimplementedBaseBallApiServer()
}

func RegisterBaseBallApiServer(s grpc.ServiceRegistrar, srv BaseBallApiServer) {
	s.RegisterService(&BaseBallApi_ServiceDesc, srv)
}

func _BaseBallApi_SelectPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseBallApiServer).SelectPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseBallApi_SelectPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseBallApiServer).SelectPlayers(ctx, req.(*SelectPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseBallApi_ServiceDesc is the grpc.ServiceDesc for BaseBallApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseBallApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BaseBallApi",
	HandlerType: (*BaseBallApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectPlayers",
			Handler:    _BaseBallApi_SelectPlayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/base_ball_api.proto",
}
