// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpc/proto/base_ball_api.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectPlayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerIds []int64 `protobuf:"varint,1,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
}

func (x *SelectPlayersRequest) Reset() {
	*x = SelectPlayersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_base_ball_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectPlayersRequest) ProtoMessage() {}

func (x *SelectPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_base_ball_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectPlayersRequest.ProtoReflect.Descriptor instead.
func (*SelectPlayersRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_base_ball_api_proto_rawDescGZIP(), []int{0}
}

func (x *SelectPlayersRequest) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type SelectPlayersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *SelectPlayersResponse) Reset() {
	*x = SelectPlayersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_base_ball_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectPlayersResponse) ProtoMessage() {}

func (x *SelectPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_base_ball_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectPlayersResponse.ProtoReflect.Descriptor instead.
func (*SelectPlayersResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_base_ball_api_proto_rawDescGZIP(), []int{1}
}

func (x *SelectPlayersResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position string `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_base_ball_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_base_ball_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_grpc_proto_base_ball_api_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

var File_grpc_proto_base_ball_api_proto protoreflect.FileDescriptor

var file_grpc_proto_base_ball_api_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x62, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x35, 0x0a, 0x14, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x3a, 0x0a, 0x15, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x22, 0x48, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x4f, 0x0a,
	0x0b, 0x42, 0x61, 0x73, 0x65, 0x42, 0x61, 0x6c, 0x6c, 0x41, 0x70, 0x69, 0x12, 0x40, 0x0a, 0x0d,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_base_ball_api_proto_rawDescOnce sync.Once
	file_grpc_proto_base_ball_api_proto_rawDescData = file_grpc_proto_base_ball_api_proto_rawDesc
)

func file_grpc_proto_base_ball_api_proto_rawDescGZIP() []byte {
	file_grpc_proto_base_ball_api_proto_rawDescOnce.Do(func() {
		file_grpc_proto_base_ball_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_base_ball_api_proto_rawDescData)
	})
	return file_grpc_proto_base_ball_api_proto_rawDescData
}

var file_grpc_proto_base_ball_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_proto_base_ball_api_proto_goTypes = []interface{}{
	(*SelectPlayersRequest)(nil),  // 0: SelectPlayersRequest
	(*SelectPlayersResponse)(nil), // 1: SelectPlayersResponse
	(*Player)(nil),                // 2: Player
}
var file_grpc_proto_base_ball_api_proto_depIdxs = []int32{
	2, // 0: SelectPlayersResponse.players:type_name -> Player
	0, // 1: BaseBallApi.SelectPlayers:input_type -> SelectPlayersRequest
	1, // 2: BaseBallApi.SelectPlayers:output_type -> SelectPlayersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_base_ball_api_proto_init() }
func file_grpc_proto_base_ball_api_proto_init() {
	if File_grpc_proto_base_ball_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_base_ball_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectPlayersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_base_ball_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectPlayersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_base_ball_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_base_ball_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_base_ball_api_proto_goTypes,
		DependencyIndexes: file_grpc_proto_base_ball_api_proto_depIdxs,
		MessageInfos:      file_grpc_proto_base_ball_api_proto_msgTypes,
	}.Build()
	File_grpc_proto_base_ball_api_proto = out.File
	file_grpc_proto_base_ball_api_proto_rawDesc = nil
	file_grpc_proto_base_ball_api_proto_goTypes = nil
	file_grpc_proto_base_ball_api_proto_depIdxs = nil
}
