apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: baseball-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: baseball-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
