apiVersion: v1
kind: Service
metadata:
  name: baseball-api
  labels:
    name: baseball-api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: baseball-api

