// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: get_books.sql

package dbgen

import (
	"context"
)

const getBook = `-- name: GetBook :one
SELECT
   id, title, author, publisher, publication_year, genre, isbn
FROM
   books
WHERE
   id = ?
LIMIT
   1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Publisher,
		&i.PublicationYear,
		&i.Genre,
		&i.Isbn,
	)
	return i, err
}
