// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package dbgen

import (
	"context"
)

type Querier interface {
	GetBook(ctx context.Context, id int32) (Book, error)
}

var _ Querier = (*Queries)(nil)
