/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/players": {
    /** 選手を作成する */
    post: {
      parameters: {
        body: {
          /** User information */
          player: definitions["internal.createPlayerRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["internal.createPlayerResponse"];
        };
      };
    };
  };
  "/players/{id}": {
    /** 選手を作成する */
    get: {
      parameters: {
        path: {
          /** id */
          id: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["internal.fetchPlayerResponse"];
        };
      };
    };
  };
  "/players/crawl": {
    /** "https://baseball-data.com/stats/hitter-%v/tpa-1.html" から選手情報をクロールする */
    post: {
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/players/search": {
    /** 選手を作成する */
    get: {
      parameters: {
        query: {
          limit?: number;
          max_hits?: number;
          max_home_runs?: number;
          max_runs_batted_in?: number;
          min_hits?: number;
          min_home_runs?: number;
          min_runs_batted_in?: number;
          sort_field?: string;
          sort_order?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["internal.searchPlayerResponse"];
        };
      };
    };
  };
}

export interface definitions {
  "internal.createPlayerRequest": {
    /**
     * Format: int64
     * @example 100
     */
    at_bats: number;
    /**
     * Format: int64
     * @example 30
     */
    hits: number;
    /**
     * Format: int64
     * @example 5
     */
    home_runs: number;
    /**
     * Format: string
     * @example 田中太郎
     */
    name: string;
    /**
     * Format: int64
     * @example 20
     */
    runs_batted_in: number;
    /**
     * Format: int64
     * @example 1
     */
    uniform_number: number;
    /**
     * Format: int64
     * @example 10
     */
    walks: number;
  };
  "internal.createPlayerResponse": {
    player?: definitions["internal.playerResponseModel"];
  };
  "internal.fetchPlayerResponse": {
    player?: definitions["internal.playerResponseModel"];
  };
  "internal.playerResponseModel": {
    at_bats?: number;
    hits?: number;
    home_runs?: number;
    id?: string;
    name?: string;
    runs_batted_in?: number;
    uniform_number?: number;
    walks?: number;
  };
  "internal.searchPlayerResponse": {
    players?: definitions["internal.playerResponseModel"][];
  };
}

export interface operations {}

export interface external {}
