version: "3"
services:
  go-api:
    build:
      context: ../
      dockerfile: tools/api/Dockerfile
    ports:
      - "50051:50051"
    # depends_on:
    #   - mysql
    #   - redis
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes: 
      - ..:/app

      


  # mysql:
  #   image: mysql:8.0.25
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=mydb

  # redis:
  #   container_name: go_redis
  #   image: redis:4.0
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     csw_nw:
