definitions:
  internal.createPlayerRequest:
    properties:
      at_bats:
        example: 100
        format: int64
        type: integer
      hits:
        example: 30
        format: int64
        type: integer
      home_runs:
        example: 5
        format: int64
        type: integer
      name:
        example: 田中太郎
        format: string
        type: string
      runs_batted_in:
        example: 20
        format: int64
        type: integer
      uniform_number:
        example: 1
        format: int64
        type: integer
      walks:
        example: 10
        format: int64
        type: integer
    required:
    - at_bats
    - hits
    - home_runs
    - name
    - runs_batted_in
    - uniform_number
    - walks
    type: object
  internal.createPlayerResponse:
    properties:
      at_bats:
        type: integer
      hits:
        type: integer
      home_runs:
        type: integer
      id:
        type: string
      name:
        type: string
      runs_batted_in:
        type: integer
      uniform_number:
        type: integer
      walks:
        type: integer
    type: object
info:
  contact: {}
paths:
  /players:
    post:
      consumes:
      - application/json
      description: プレイヤーを作成する
      parameters:
      - description: User information
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/internal.createPlayerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal.createPlayerResponse'
      summary: プレイヤーを作成する
      tags:
      - players
swagger: "2.0"
